axis_linear: 1
scale_linear: 0.3
scale_linear_turbo: 0.3

axis_angular: 2
scale_angular: 0.5
scale_angular_turbo: 0.8

enable_button: 4  # L2 shoulder button
enable_turbo_button: 6  # L1 shoulder button
