ekf_se_odom:
  frequency: 30
  sensor_timeout: 0.1
  transform_timeout: 0.0
  two_d_mode: true
  print_diagnostics: true
  transform_time_offset: 0.1
  predict_to_current_time: true
  debug: false
  
  map_frame: map
  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom
  
  odom0: arosrobot_velocity_controller/odom
  odom0_config: [false, false, false,
                 false, false, false,
                 true, true, false,
                 false, false, true,
                 false, false, false]
  odom0_differential: false
  odom0_nodelay: true 
  odom0_queue_size: 10
  odom0_relative: false
 

  imu0: um7/imu/data
  imu0_config: [false, false, false,
                true,  true,   true,
                false, false, false,
                true, true, true,
                false, false, false]
  imu0_differential: false
  imu0_relative: false
  imu0_nodelay: true
  imu0_queue_size: 10
  imu0_remove_gravitational_acceleration: true

ekf_se_map:
  frequency: 10 
  transform_time_offset: 0.1
  predict_to_current_time: true
  sensor_timeout: 0.1
  two_d_mode: true
  transform_timeout: 0.0
  print_diagnostics: true
  debug: false

  map_frame: map
  odom_frame: odom
  base_link_frame: base_link
  world_frame: map

  odom0: arosrobot_velocity_controller/odom
  odom0_config: [false, false, false,
                 false, false, false,
                 true,  true, false,
                 false, false, true,
                 false, false, false]
  odom0_differential: false
  odom0_nodelay: true 
  odom0_queue_size: 10
  odom0_relative: false

  #odom1: odometry/gps 
  #odom1_config: [true,  true,  false,
  #               false, false, false,
  #               false, false, false,
  #               false, false, false,
  #               false, false, false]
  #odom1_queue_size: 10
  #odom1_nodelay: true
  #odom1_differential: false
  #odom1_relative: false

  pose0: amcl_pose
  pose0_config: [true,  true,  false,
                 false, false, true,
                 false, false, false,
                 false, false, false,
                 false, false, false]
  pose0_differential: false
  pose0_nodelay: true
  pose0_queue_size: 10
  pose0_relative: false
  pose0_rejection_threshold: 2.0

  imu0: um7/imu/data 
  imu0_config: [false, false, false,
                true,  true,  true,
                false, false, false,
                true,  true,  true,
                false,  false,  false]
  imu0_nodelay: true
  imu0_differential: false 
  imu0_relative: false
  imu0_queue_size: 10
  imu0_remove_gravitational_acceleration: true

