axis_linear: 1
scale_linear: 0.8
scale_linear_turbo: 2.5

axis_angular: 2
scale_angular: 1
scale_angular_turbo: 1 

enable_button: 4  # L2 shoulder button
enable_turbo_button: 6  # L1 shoulder button
