<?xml version="1.0"?>
<robot name="icerobot" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find icerobot_description)/urdf/azure_camera.urdf.xacro" />
  <xacro:include filename="$(find icerobot_description)/urdf/wheels.urdf.xacro" />
  <xacro:include filename="$(find icerobot_description)/urdf/imu.urdf.xacro" />
  <xacro:include filename="$(find icerobot_description)/urdf/lidar.urdf.xacro" />

  <!-- Base Size -->
  <xacro:property name="base_x_size" value="0.96520000" />
  <xacro:property name="base_y_size" value="0.63500000" />
  <xacro:property name="base_z_size" value="0.6154100" />

  <!-- Platform Size -->
  <xacro:property name="platform_x_size" value="0.320000" />
  <xacro:property name="platform_y_size" value="0.63500000" />
  <xacro:property name="platform_z_size" value="1.4000000" />
  
  <!-- Wheel Mounting Positions -->
  <xacro:property name="wheelbase" value="0.3080" />
  <xacro:property name="track" value="0.33" />
  <xacro:property name="wheel_vertical_offset" value="0.07" />

  <!-- Wheel Properties -->
  <xacro:property name="wheel_length" value="0.11430" />
  <xacro:property name="wheel_radius" value="0.167" />

  <!-- Base inertia properties -->
  <xacro:property name="mass_base" value="34.33" />
  <xacro:property name="ixx_base" value="2.4304" />
  <xacro:property name="ixy_base" value="0.5116" />
  <xacro:property name="ixz_base" value="0.0091" />
  <xacro:property name="iyy_base" value="3.7564" />
  <xacro:property name="iyz_base" value="-0.0016" />
  <xacro:property name="izz_base" value="3.8077" />

  <!-- Platform inertia properties -->
  <xacro:property name="mass_platform" value="49.4938" />
  <xacro:property name="ixx_platform" value="16.83" />
  <xacro:property name="ixy_platform" value="0.3363" />
  <xacro:property name="ixz_platform" value="0.1616" />
  <xacro:property name="iyy_platform" value="3.9954" />
  <xacro:property name="iyz_platform" value="6.3377" />
  <xacro:property name="izz_platform" value="13.2782" />
  
  <!-- Wheel inertia properties -->
  <xacro:property name="mass_wheel" value="4" />
  <xacro:property name="ixx_wheel" value="0.0553" />
  <xacro:property name="ixy_wheel" value="0" />
  <xacro:property name="ixz_wheel" value="0" />
  <xacro:property name="iyy_wheel" value="0.0315" />
  <xacro:property name="iyz_wheel" value="0" />
  <xacro:property name="izz_wheel" value="0.0315" />
  
  <xacro:arg name="robot_namespace" default="/" />
  <xacro:property name="PI" value="3.14159"/>

  <!-- Robot base -->
  <link name="base_link">
    <visual>
      <origin rpy="0 0 ${PI}" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://icerobot_description/meshes/base.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_z_size/2}" rpy="0 0 0" />
      <geometry>
        <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
      </geometry>
    </collision>
  </link>

  <link name="inertial_link">
    <inertial>
      <mass value="${mass_base}" />
      <origin xyz="-0.00065 -0.085 0.062" rpy="0 0 ${PI}"/>
      <inertia ixx="${ixx_base}" ixy="${ixy_base}" ixz="${ixz_base}" iyy="${iyy_base}" iyz="${iyz_base}" izz="${izz_base}"/>
    </inertial>
  </link>

  <joint name="inertial_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="inertial_link" />
  </joint>

  <!-- Sensor Platform -->  
  <joint name="platform_to_base" type="fixed">
    <parent link="base_link"/>
    <child link="platform"/>
    <origin rpy="0 0 0" xyz="-0.12 0.01 0.4"/>
  </joint>
  
  <link name="platform">
    <visual>
      <origin rpy="0 0 ${PI}" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://icerobot_description/meshes/platform.dae"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="${platform_x_size} ${platform_y_size} ${platform_z_size}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0.1 0 ${(platform_z_size/2)}"/>
    </collision>
    <inertial>
      <mass value="${mass_platform}" />
      <origin xyz="0 0 0" />
      <inertia ixx="${ixx_platform}" ixy="${ixy_platform}" ixz="${ixz_platform}" iyy="${iyy_platform}" iyz="${iyz_platform}" izz="${izz_platform}"/>
    </inertial>
  </link>

  <gazebo reference="platform">
    <material>Gazebo/Grey</material>
  </gazebo>

  <!-- Base footprint is on the ground under the robot -->
  <link name="base_footprint"/>

  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 -0.1" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="base_footprint" />
  </joint>

  <!-- Wheel xacro -->
  <xacro:wheel prefix="front" suffix="left" reflect_side="1" reflect_front="1"/>
  <xacro:wheel prefix="rear" suffix="left" reflect_side="1" reflect_front="-1"/>
  <xacro:wheel prefix="front" suffix="right" reflect_side="-1" reflect_front="1"/>
  <xacro:wheel prefix="rear" suffix="right" reflect_side="-1" reflect_front="-1"/>
  
  <!-- add topic_kinect="kinect" for kinect camera -->

  <xacro:rgbd_cameras topic_azure="azure" parent_link="base_link"/>
  <xacro:imu_setup topic_imu_um7="um7/imu/data" topic_imu_azure="azure/imu/data" parent_link="base_link"/>
  <xacro:lidar_setup topic_lidar_vlp16="vlp16/scan" topic_lidar_rplidar="rplidar/scan" parent_link="base_link"/>

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>$(arg robot_namespace)</robotNamespace>
      <legacyModeNS>true</legacyModeNS>
    </plugin>
  </gazebo>

  
  <gazebo>
    <plugin name="gps_controller" filename="libhector_gazebo_ros_gps.so">
      <robotNamespace>$(arg robot_namespace)</robotNamespace>
      <updateRate>5</updateRate>
      <bodyName>base_link</bodyName>
      <frameId>base_link</frameId>
      <topicName>navsat/fix</topicName>
      <velocityTopicName>navsat/vel</velocityTopicName>
      <referenceLatitude>42.86</referenceLatitude>
      <referenceLongitude>-80.27</referenceLongitude>
      <referenceHeading>0</referenceHeading>
      <referenceAltitude>0</referenceAltitude>
      <drift>0.0001 0.0001 0.0001</drift>
    </plugin>
  </gazebo>
  

</robot>

