<?xml version="1.0"?>
<robot name="icerobot" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find icerobot_description)/urdf/azure_camera.urdf.xacro" />

  <!-- Base Size -->
  <xacro:property name="base_x_size" value="0.96520000" />
  <xacro:property name="base_y_size" value="0.63500000" />
  <xacro:property name="base_z_size" value="0.6154100" />

  <!-- Platform Size -->
  <xacro:property name="platform_x_size" value="0.320000" />
  <xacro:property name="platform_y_size" value="0.63500000" />
  <xacro:property name="platform_z_size" value="1.4000000" />
  
  <!-- Wheel Mounting Positions -->
  <xacro:property name="wheelbase" value="0.3080" />
  <xacro:property name="track" value="0.33" />
  <xacro:property name="wheel_vertical_offset" value="0.07" />

  <!-- Wheel Properties -->
  <xacro:property name="wheel_length" value="0.11430" />
  <xacro:property name="wheel_radius" value="0.167" />

  <!-- Base inertia properties -->
  <xacro:property name="mass_base" value="34.33" />
  <xacro:property name="ixx_base" value="2.4304" />
  <xacro:property name="ixy_base" value="0.5116" />
  <xacro:property name="ixz_base" value="0.0091" />
  <xacro:property name="iyy_base" value="3.7564" />
  <xacro:property name="iyz_base" value="-0.0016" />
  <xacro:property name="izz_base" value="3.8077" />

  <!-- Platform inertia properties -->
  <xacro:property name="mass_platform" value="49.4938" />
  <xacro:property name="ixx_platform" value="16.83" />
  <xacro:property name="ixy_platform" value="0.3363" />
  <xacro:property name="ixz_platform" value="0.1616" />
  <xacro:property name="iyy_platform" value="3.9954" />
  <xacro:property name="iyz_platform" value="6.3377" />
  <xacro:property name="izz_platform" value="13.2782" />
  
  <!-- Wheel inertia properties -->
  <xacro:property name="mass_wheel" value="4" />
  <xacro:property name="ixx_wheel" value="0.0553" />
  <xacro:property name="ixy_wheel" value="0" />
  <xacro:property name="ixz_wheel" value="0" />
  <xacro:property name="iyy_wheel" value="0.0315" />
  <xacro:property name="iyz_wheel" value="0" />
  <xacro:property name="izz_wheel" value="0.0315" />
  
  <xacro:arg name="robot_namespace" default="/" />
  <xacro:property name="PI" value="3.14159"/>

  <!-- Robot base -->
  <link name="base_link">
    <visual>
      <origin rpy="0 0 ${PI}" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://icerobot_description/meshes/base.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_z_size/2}" rpy="0 0 0" />
      <geometry>
        <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
      </geometry>
    </collision>
  </link>

  <link name="inertial_link">
    <inertial>
      <mass value="${mass_base}" />
      <origin xyz="-0.00065 -0.085 0.062" rpy="0 0 ${PI}"/>
      <inertia ixx="${ixx_base}" ixy="${ixy_base}" ixz="${ixz_base}" iyy="${iyy_base}" iyz="${iyz_base}" izz="${izz_base}"/>
    </inertial>
  </link>

  <joint name="inertial_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="inertial_link" />
  </joint>

  <!-- Wheel macros -->
  <xacro:macro name="wheel" params="prefix suffix reflect_side reflect_front">
    <link name="${prefix}_${suffix}_wheel">
      <visual>
       <origin xyz="0 0 0" rpy="0 0 ${reflect_side*PI/2+PI}" />
       <geometry>
         <mesh filename="package://icerobot_description/meshes/wheel.dae"/>
       </geometry>
      </visual>
      <collision>
	      <origin xyz="0 ${reflect_side*0.04} 0" rpy="${PI/2} 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="${mass_wheel}" />
        <origin xyz="0 0 0" />
        <inertia ixx="${ixx_wheel}" ixy="${ixy_wheel}" ixz="${ixz_wheel}" iyy="${iyy_wheel}" iyz="${iyz_wheel}" izz="${izz_wheel}"/>
      </inertial>
    </link>
    
    <joint name="${prefix}_${suffix}_wheel_joint" type="continuous">
      <axis xyz="0 1 0" rpy="0 0 0" />
      <parent link="base_link"/>
      <child link="${prefix}_${suffix}_wheel"/>
      <origin xyz="${reflect_front*wheelbase} ${reflect_side*track} ${wheel_vertical_offset}" rpy="0 0 0"/>
    </joint>

    <!-- Gazebo xacro -->
    <!-- Wheel parameters -->
    <gazebo reference="${prefix}_${suffix}_wheel">
      <mu1 value="1.0"/>
      <mu2 value="0.5"/>
      <kp value="100000000.0" />
      <kd value="1.0" />
      <fdir1 value="1 0 0"/>
    </gazebo>

    <transmission name="${prefix}_${suffix}_wheel_trans" type="SimpleTransmission">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="${prefix}_${suffix}_wheel_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      <joint name="${prefix}_${suffix}_wheel_joint">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
    </transmission>


  </xacro:macro>
  <xacro:wheel prefix="front" suffix="left" reflect_side="1" reflect_front="1"/>
  <xacro:wheel prefix="rear" suffix="left" reflect_side="1" reflect_front="-1"/>
  <xacro:wheel prefix="front" suffix="right" reflect_side="-1" reflect_front="1"/>
  <xacro:wheel prefix="rear" suffix="right" reflect_side="-1" reflect_front="-1"/>
  
  <!-- Sensor Platform -->  
  <joint name="platform_to_base" type="fixed">
    <parent link="base_link"/>
    <child link="platform"/>
    <origin rpy="0 0 0" xyz="-0.12 0.01 0.4"/>
  </joint>
  
  <link name="platform">
    <visual>
      <origin rpy="0 0 ${PI}" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://icerobot_description/meshes/platform.dae"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="${platform_x_size} ${platform_y_size} ${platform_z_size}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="-0.1 0 ${(platform_z_size/2)}"/>
    </collision>
    <inertial>
      <mass value="${mass_platform}" />
      <origin xyz="0 0 0" />
      <inertia ixx="${ixx_platform}" ixy="${ixy_platform}" ixz="${ixz_platform}" iyy="${iyy_platform}" iyz="${iyz_platform}" izz="${izz_platform}"/>
    </inertial>
  </link>

  <gazebo reference="platform">
    <material>Gazebo/Grey</material>
  </gazebo>

  <!-- Base footprint is on the ground under the robot -->
  <link name="base_footprint"/>

  <joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 -0.1" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="base_footprint" />
  </joint>

  <!-- IMU Link is the standard mounting position for the UM6 IMU.-->
  <!-- Can be modified with environment variables in /etc/ros/setup.bash -->
  <link name="imu_link"/>
  <joint name="imu_joint" type="fixed">
	  <origin xyz="-0.10 0.007 1.24" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="imu_link" />
  </joint>
  <gazebo reference="imu_link">
  </gazebo>

  <joint name="scan_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_scan"/>
    <origin xyz="-0.375 0.008 1.322" rpy="0 ${-PI/2} 0"/>
  </joint>

  <link name="base_scan">
    <visual>
      <origin xyz="0 0 -0.1" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://icerobot_description/meshes/lidar.dae"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 -0.1" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.15" radius="0.045"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.83" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.002" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.002" />
    </inertial>
  </link>

  <xacro:rgbd_cameras topic_azure="azure" topic_kinect="kinect" parent_link="base_link"/>

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>$(arg robot_namespace)</robotNamespace>
      <legacyModeNS>true</legacyModeNS>
    </plugin>
  </gazebo>

  <gazebo>
    <plugin name="imu_controller" filename="libhector_gazebo_ros_imu.so">
      <robotNamespace>$(arg robot_namespace)</robotNamespace>
      <updateRate>20.0</updateRate>
      <bodyName>base_link</bodyName>
      <topicName>imu/data</topicName>
      <xyzOffset>0 0 0</xyzOffset>
      <rpyOffset>0 0 0</rpyOffset>
      <accelDrift>0.5 0.5 0.5</accelDrift>
      <accelGaussianNoise>0.05 0.05 0.05</accelGaussianNoise>
      <rateDrift>0.5 0.5 0.5 </rateDrift>
      <rateGaussianNoise>0.05 0.05 0.05 </rateGaussianNoise>
      <headingDrift>0.005</headingDrift>
      <headingGaussianNoise>0.005</headingGaussianNoise>
    </plugin>
  </gazebo>
  
  <gazebo>
    <plugin name="gps_controller" filename="libhector_gazebo_ros_gps.so">
      <robotNamespace>$(arg robot_namespace)</robotNamespace>
      <updateRate>5</updateRate>
      <bodyName>base_link</bodyName>
      <frameId>base_link</frameId>
      <topicName>navsat/fix</topicName>
      <velocityTopicName>navsat/vel</velocityTopicName>
      <referenceLatitude>42.86</referenceLatitude>
      <referenceLongitude>-80.27</referenceLongitude>
      <referenceHeading>0</referenceHeading>
      <referenceAltitude>0</referenceAltitude>
      <drift>0.0001 0.0001 0.0001</drift>
    </plugin>
  </gazebo>
  
  <gazebo reference="base_scan">
    <sensor type="ray" name="velodyne_VLP16">
      <pose>2 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>1875</samples>
            <resolution>1</resolution>
	    <min_angle>-${PI}</min_angle>
	    <max_angle>${PI}</max_angle>
          </horizontal>
          <vertical>
            <samples>16</samples>
            <resolution>1</resolution>
            <min_angle>-${15.0*PI/180.0}</min_angle>
            <max_angle> ${15.0*PI/180.0}</max_angle>
          </vertical>
        </scan>
        <range>
          <min>0.3</min>
          <max>2</max>
          <resolution>0.001</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.0</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_laser_controller" filename="libgazebo_ros_laser.so">
	<robotNamespace>$(arg robot_namespace)</robotNamespace>
	<topicName>scan</topicName>
        <frameName>base_scan</frameName>
	<min_range>0.9</min_range>
	<max_range>2</max_range>
        <gaussianNoise>0.008</gaussianNoise>
      </plugin>
    </sensor>
  </gazebo> 

</robot>

