map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: odom

two_d_mode: true

frequency: 30
sensor_timeout: 0.1

odom0: icerobot_velocity_controller/odom
odom0_config: [false, false, false,
               false, false, false,
               true, true, false,
               false, false, true,
               false, false, false]
odom0_differential: false
odom0_nodelay: true
odom0_queue_size: 10
odom0_relative: false

imu0: um7/imu/data
imu0_config: [false, false, false,
              true,  true,  true,
              false, false, false,
              true,  true,  true,
              false, false, false]
imu0_differential: true
imu0_relative: false
imu0_nodelay: false
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: true

