controller_frequency: 5.0
recovery_behaviour_enabled: true

NavfnROS:
  allow_unknown: true 
  default_tolerance: 0.5 


DWAPlannerROS:
  # Robot configuration parameters  
  acc_lim_x: 5.0
  acc_lim_y: 0.0
  acc_lim_th: 5.0

  min_vel_trans: 0.1
  max_vel_trans: 2.5
  min_vel_x: 0.0
  max_vel_x: 2.5
  min_vel_y: 0.0
  max_vel_y: 0.0
  min_vel_theta: 0.4
  min_rot_vel: 0.4
  max_vel_theta: 1.5

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false

  # # Forward Simulation Parameters
  sim_time: 2.0
  sim_granularity: 0.025
  vx_samples: 10
  vy_samples: 0
  vtheta_samples: 20
  penalize_negative_x: true

  # Trajectory scoring parameters
  path_distance_bias: 32.0 
  goal_distance_bias: 24.0 
  occdist_scale: 0.5 
  forward_point_distance: 0.325 
  stop_time_buffer: 0.2  
  scaling_speed: 0.25 
  max_scaling_factor: 0.2 

  publish_cost_grid: true
  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05 
  prune_plan: true
