talons:
    back_right:
        id: 02
        inverted: True 
    back_left:
        id: 01
        inverted: False 
    front_right:
        id: 04
        inverted: True
    front_left:
        id: 03
        inverted: False 
